version: 2

models:
  - name: src_international_top_terms
    description: Bronze model containing the latest available international Google Trends top terms.

  - name: src_international_top_rising_terms
    description: Bronze model containing the latest available international Google Trends rising terms.

  - name: src_top_terms
    description: Bronze model containing the latest available United States Google Trends top terms.

  - name: src_top_rising_terms
    description: Bronze model containing the latest available United States Google Trends rising terms.